### ISSUE TITLE
Problem z wyszukiwaniem wielu podmiotów po numerze NIP

### ISSUE THREAD

**Issue by piterq** [tobik312/GUS-lib#2]
Wyszukiwanie wielu podmiotów po numerze NIP nie działa.
użycie:
`List<Podmiot> pNIP = gusClient.SzukajPodmiotyNip("2588781019", "6959319962");`
zwraca błąd:
```
System.ArgumentNullException: 'Wartość nie może być zerowa.
Nazwa parametru: value'
```
Metoda SzukajPodmioty również zwraca ten sam błąd.

**Comment by tobik312** [comment]
Rozwiązane w #4
